baseURL = "https://jonnycosgrove.com/"
languageCode = "en-us"
title = "Jonny Cosgrove"
theme = "PaperMod"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
  [[menu.main]]
    name = "Grok Quote"
    url = "/grok-quote/"
    weight = 5